# 1 weeks data of Fitbit
SAMPLE_FITBIT_RESPONSE = [
    {
        "activities": [],
        "summary": {
            "activeScore": -1,
            "activityCalories": 0,
            "caloriesBMR": 1766,
            "caloriesOut": 1766,
            "distances": [
                {"activity": "total", "distance": 0},
                {"activity": "tracker", "distance": 0},
                {"activity": "loggedActivities", "distance": 0},
                {"activity": "veryActive", "distance": 0},
                {"activity": "moderatelyActive", "distance": 0},
                {"activity": "lightlyActive", "distance": 0},
                {"activity": "sedentaryActive", "distance": 0},
            ],
            "fairlyActiveMinutes": 0,
            "lightlyActiveMinutes": 0,
            "marginalCalories": 0,
            "sedentaryMinutes": 1440,
            "steps": 0,
            "veryActiveMinutes": 0,
        },
    },
    {
        "activities": [],
        "summary": {
            "activeScore": -1,
            "activityCalories": 0,
            "caloriesBMR": 1761,
            "caloriesOut": 1761,
            "distances": [
                {"activity": "total", "distance": 0},
                {"activity": "tracker", "distance": 0},
                {"activity": "loggedActivities", "distance": 0},
                {"activity": "veryActive", "distance": 0},
                {"activity": "moderatelyActive", "distance": 0},
                {"activity": "lightlyActive", "distance": 0},
                {"activity": "sedentaryActive", "distance": 0},
            ],
            "fairlyActiveMinutes": 0,
            "lightlyActiveMinutes": 0,
            "marginalCalories": 0,
            "sedentaryMinutes": 1440,
            "steps": 0,
            "veryActiveMinutes": 0,
        },
    },
    {
        "activities": [],
        "goals": {
            "activeMinutes": 30,
            "caloriesOut": 2681,
            "distance": 8.05,
            "steps": 10000,
        },
        "summary": {
            "activeScore": -1,
            "activityCalories": 0,
            "caloriesBMR": 501,
            "caloriesOut": 501,
            "distances": [
                {"activity": "total", "distance": 0},
                {"activity": "tracker", "distance": 0},
                {"activity": "loggedActivities", "distance": 0},
                {"activity": "veryActive", "distance": 0},
                {"activity": "moderatelyActive", "distance": 0},
                {"activity": "lightlyActive", "distance": 0},
                {"activity": "sedentaryActive", "distance": 0},
            ],
            "fairlyActiveMinutes": 0,
            "lightlyActiveMinutes": 0,
            "marginalCalories": 0,
            "sedentaryMinutes": 411,
            "steps": 0,
            "veryActiveMinutes": 0,
        },
    },
]
